spring:
  application:
    name: microservicio-zuul

server.port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    usuarios:
      service-id: microservicio-usuarios
      path: /api/alumnos/**
    cursos:
      service-id: microservicio-cursos
      path: /api/cursos/**
    examenes:
      service-id: microservicio-examenes
      path: /api/examenes/**